/**
 * qcpt 全局组件类型声明
 * 
 * This file is auto-generated by scripts/generate-global-types.js
 * Do not edit manually, changes will be overwritten on next build
 * 
 * Compatible with Vue 3.2+
 */

import type {
  JChBarProps,
  JChBarSlots,
} from './components/j-ch-bar/types';

import type {
  JChBarLineProps,
  JChBarLineSlots,
} from './components/j-ch-bar-line/types';

import type {
  JChBubbleProps,
  JChBubbleSlots,
} from './components/j-ch-bubble/types';

import type {
  JChLineProps,
  JChLineSlots,
} from './components/j-ch-line/types';

import type {
  JChPieDoughnutProps,
  JChPieDoughnutSlots,
} from './components/j-ch-pie-doughnut/types';

import type {
  JChRadarProps,
  JChRadarSlots,
} from './components/j-ch-radar/types';

import type {
  JCNestedSelectProps,
  JCNestedSelectEmits,
} from './components/j-c-nested-select/types';

import type {
  JCTableProps,
} from './components/j-c-table/types';

import type {
  JCTooltipProps,
  JCTooltipSlots,
  JCTooltipEmits,
} from './components/j-c-tooltip/types';

import type {
  JCTooltipEllipsisProps,
  JCTooltipEllipsisSlots,
} from './components/j-c-tooltip-ellipsis/types';

import type {
  JQButtonTemplateProps,
  JQButtonSlots,
  JQButtonEmits,
} from './components/j-q-button/types';

import type {
  JQButtonDropdownProps,
  JQButtonDropdownSlots,
  JQButtonDropdownEmits,
} from './components/j-q-button-dropdown/types';

import type {
  JQConfirmTemplateProps,
  JQConfirmSlots,
  JQConfirmEmits,
} from './components/j-q-confirm/types';

declare module 'vue' {
  export interface GlobalComponents {
    /**
     * JChBar - JChBar 组件
     */
    JChBar: new () => {
      $props: JChBarProps;
      $slots: JChBarSlots;
      $emit: {};
    };

    /**
     * JChBarLine - JChBarLine 组件
     */
    JChBarLine: new () => {
      $props: JChBarLineProps;
      $slots: JChBarLineSlots;
      $emit: {};
    };

    /**
     * JChBubble - JChBubble 组件
     */
    JChBubble: new () => {
      $props: JChBubbleProps;
      $slots: JChBubbleSlots;
      $emit: {};
    };

    /**
     * JChLine - JChLine 组件
     */
    JChLine: new () => {
      $props: JChLineProps;
      $slots: JChLineSlots;
      $emit: {};
    };

    /**
     * JChPieDoughnut - JChPieDoughnut 组件
     */
    JChPieDoughnut: new () => {
      $props: JChPieDoughnutProps;
      $slots: JChPieDoughnutSlots;
      $emit: {};
    };

    /**
     * JChRadar - JChRadar 组件
     */
    JChRadar: new () => {
      $props: JChRadarProps;
      $slots: JChRadarSlots;
      $emit: {};
    };

    /**
     * JCNestedSelect - JCNestedSelect 组件
     */
    JCNestedSelect: new () => {
      $props: JCNestedSelectProps;
      $slots: {};
      $emit: JCNestedSelectEmits;
    };

    /**
     * JCTable - JCTable 组件
     */
    JCTable: new () => {
      $props: JCTableProps;
      $slots: {};
      $emit: {};
    };

    /**
     * JCTooltip - JCTooltip 组件
     */
    JCTooltip: new () => {
      $props: JCTooltipProps;
      $slots: JCTooltipSlots;
      $emit: JCTooltipEmits;
    };

    /**
     * JCTooltipEllipsis - JCTooltipEllipsis 组件
     */
    JCTooltipEllipsis: new () => {
      $props: JCTooltipEllipsisProps;
      $slots: JCTooltipEllipsisSlots;
      $emit: {};
    };

    /**
     * JQButton - JQButton 组件
     */
    JQButton: new () => {
      $props: JQButtonTemplateProps;
      $slots: JQButtonSlots;
      $emit: JQButtonEmits;
    };

    /**
     * JQButtonDropdown - JQButtonDropdown 组件
     */
    JQButtonDropdown: new () => {
      $props: JQButtonDropdownProps;
      $slots: JQButtonDropdownSlots;
      $emit: JQButtonDropdownEmits;
    };

    /**
     * JQConfirm - JQConfirm 组件
     */
    JQConfirm: new () => {
      $props: JQConfirmTemplateProps;
      $slots: JQConfirmSlots;
      $emit: JQConfirmEmits;
    };
  }
}

export {};
